### ISSUE TITLE
增添事件的时候旋转出现重叠

### ISSUE THREAD

**Issue by MooWantFree** [chanjsq/one-hundred#3]
您这个项目默认是50个事情, 我想在此基础上再加50个一共100个, 但我发现这样的话就会两个事件重叠在一起(见图), 具体应该是修改ListItem.vue中引用的CircleType, 但我不知道怎么修改半径才能达到这个目的, 能不能麻烦告知一下怎么样能实现100个事件而不发生重叠, 万分感谢
![Snipaste_2020-06-23_15-48-23](https://user-images.githubusercontent.com/46401523/85375832-735eaf00-b569-11ea-8357-93a5e7559eb5.png)

**Comment by chanjsq** [comment]
![image](https://user-images.githubusercontent.com/30150098/85399391-53d77e80-b589-11ea-92ed-c67fd7f89bd8.png)
你好，如图把绿色再改回红色，可能就可以 100 件了。

**Comment by MooWantFree** [comment]
万分感谢, 已经可以了
![Snipaste_2020-06-23_19-53-26](https://user-images.githubusercontent.com/46401523/85400604-43280800-b58b-11ea-82c6-b0abf87e8e50.png)

**Comment by chanjsq** [comment]
赞
